# This is a basic workflow to help you get started with Actions

name: k6

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run-k6-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: theboi/github-update-readme@v1.0
        env: ${{ secrets.GITHUB_TOKEN }}
        with: 
          header: "Hey!"
          subhead: "Test if this workflow notifies developer to update the readme.md"
          footer: "**Lets see the final result**"
      
      
      # - run: ls -la
      # - name: Run load test using action code from commit
      #   uses: ./.github/actions
      #   with:
      #     cloud: false
      #     token: ${{ secrets.K6_TOKEN }}
      #     flags: --vus 1 --duration 10s
      
