# This is a basic workflow to help you get started with Actions

name: k6

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
permissions: 
   pull-requests: write 

jobs:
  run-k6-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - run: |
      #     echo ${{ toJSON(github) }}
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          pr_number: 1
          message: |
            Hi :wave: @**${{ github.actor }}**, have you updated the [README](https://github.com/${{ github.repository }}/blob/${{ github.head_ref }}/README.md) doc!
          
      
      
      # - run: ls -la
      # - name: Run load test using action code from commit
      #   uses: ./.github/actions
      #   with:
      #     cloud: false
      #     token: ${{ secrets.K6_TOKEN }}
      #     flags: --vus 1 --duration 10s
      
